<?php

namespace App\Http\Requests;

use App\Models\Session;
use App\Rules\PartialCompletionCodeRule;
use App\Rules\SessionStartAndEndTimeRule;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\Auth;
use Illuminate\Validation\Rule;

class CreateSessionRequest extends FormRequest
{
    public function rules(): array
    {

        return [
            'tutor_id' => Rule::requiredIf(Auth::user()->hasRole(['super-admin', 'admin'])),
            'student_tutoring_package_id' => ['required', 'integer'],
            'scheduled_date' => ['required', 'date'],
            'start_time' => ['required', new SessionStartAndEndTimeRule()],
            'end_time' => ['required', new SessionStartAndEndTimeRule()],
            'tutoring_location_id' => ['required', 'integer'],
            'pre_session_notes' => ['nullable'],
            'session_completion_code' => ['nullable', 'integer'],
            'how_was_session' => ['nullable', 'integer'],
            'student_parent_session_notes' => ['nullable'],
            'homework' => ['nullable'],
            'internal_notes' => ['nullable'],
            'flag_session' => ['nullable'],
            'home_work_completed' => ['nullable'],
            'practice_test_for_homework' => ['nullable'],
            'attended_start_time' => [new PartialCompletionCodeRule()],
            'attended_end_time' => [new PartialCompletionCodeRule()],
        ];
    }

    public function authorize(): bool
    {
        return true;
    }
    public function messages()
    {
        return Session::$messages; // TODO: Change the autogenerated stub
    }
}
